files=(
"data/test1.txt"
"data/test2.txt"
"data/test3.txt"
"data/test4.txt"
"data/test5.txt"
"data/test6.txt"
"data/test_add.txt"
"data/test_subtract.txt"
"data/test_multiply.txt"
"data/test_divide.txt"
"data/test_mod.txt"
"data/test_exp.txt"
"data/test7.txt"
"data/test_and.txt"
"data/test_and_false.txt"
"data/test_not.txt"
"data/test_neq.txt"
"data/test_or.txt"
"data/test_or_false.txt"
"data/test8.txt"
"data/test9_lt10.txt"
"data/test9_lt20.txt"
"data/test9_gt30.txt"
"data/test9_noelsif.txt"
"data/test9.txt"
"data/test10.txt"
"data/test11.txt 6.8"
"data/test12.txt 16 15.9"
"data/test12_several.txt 1 2.2 3.3 4"
"data/test13.txt"
"data/test14.txt"
"data/test15.txt 1 2.5 65"
"data/test16.txt 10 -10"
"data/test16.txt 10 5"
"data/test16.txt 10 -34"
"data/test16.txt 10 0"
"data/test16.txt -55 99"
"data/test16.txt -55 -99"
"data/test16.txt -34 0"
"data/test16.txt 0 0"
"data/test16.txt 0 -1"
"data/test16.txt 0 1123"
"data/syntax1.txt"
"data/syntax2.txt"
"data/syntax3.txt 14"
"data/syntax4.txt 28"
"data/syntax5.txt"
)

for entry in "${files[@]}"; do
  # Split the entry into file and arguments
  file_and_args=($entry)
  file="${file_and_args[0]}"
  args=("${file_and_args[@]:1}")
  echo "Running test with input file: $file and args: ${args[*]}"
  ./bin/project3.elf < "$file" "${args[@]}"
  echo ""
  sleep 2
done